name: Deploy Astro site to Git artifact named `github-pages`. Here's how you can modify your workflow file:


on:
  push:
    branches: [main]

permissions:
  contents: read
  pages: write
  id-token: writegithub/workflows/deploy.yml`)
```yaml
name: Deploy Astro site to GitHub Pages

on:
  push:
    branches: [

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: $main]

permissions:
  contents: read
  pages: write
{{ steps.deployment.outputs.page_url }}
    steps:
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest      - name: Checkout
        uses: actions/checkout@
    environment:
      name: github-pages
      urlv4

      - name: Setup Node
        uses: actions/setup: ${{ steps.deployment.outputs.page_url }}
    steps-node@v4
        with:
          node-version: :
      - name: Checkout
        uses: actions/checkout@20

      - name: Install dependencies
        run: npmv4

      - name: Setup Node
        uses ci

      - name: Build with Astro
        run: npm: actions/setup-node@v4
        with:
          node-version: run build

      # Upload the artifact
      - name: Upload 20

      - name: Install dependencies
        run: artifact
        uses: actions/upload-artifact npm ci

      - name: Build with Astro
        run:@v4
        with:
          name: github-pages
 npm run build

      # Add this step to upload build output          path: ./dist # Replace './dist' with the actual build as an artifact
      - name: Upload artifact
 output directory

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: dist
